---
title: "Pardal et al. (2023) MER: Random forest models for the communities from the mid-midlittoral"
author: "ALPS"
date: "6/12/2023"
output: html_document
---

#### Loading packages
```{r}
## Setting working directory to source file location ##
rstudioapi::getActiveDocumentContext
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

library(ggplot2)
library(MASS)
library(ggeffects)
library(dplyr)
library(ggpubr)
library(tidyverse)
library(openxlsx)  
library(readxl)
library(lattice)
library(grid)
library(gridExtra)
library(tidyr)
library(viridis)
library(viridisLite)
library(ranger)
library(Rcpp)
library(vip)
library(pdp)
```

#### Mid-midlittoral
```{r mid midlittoral}

df3 <- read_excel("mid-midlittoral-data.xlsx", sheet = 1)
str(df3)

df3$site      <- as.factor(df3$site)
df3$subregion <- as.factor(df3$subregion)
df3$region    <- as.factor(df3$region)

df3 <- df3 %>% 
       mutate_at(c(4:29), as.numeric)

str(df3)

df3_N <- aggregate(CCA ~ site, data = df3, length)

## Check N per site ##
rm(df3_N)
```


#### Mid-midlittoral: Chthamalus bisinuatus
```{r  C. bisinuatus}

cht_data <- subset(df3, select = c(5, 19:25))
cht_data <- as.data.frame(cht_data)
str(cht_data)

# train a default random forest model
  cht_rf1 <- ranger(
  formula = C.bisinuatus ~ ., 
  data = cht_data,
  num.trees = 2500,
  importance = "permutation",
  seed = 8558)

print(cht_rf1)
(default_rmse <- sqrt(cht_rf1$prediction.error))# get OOB RMSE for further comparison ##

# create hyperparameter grid
hyper_grid <- expand.grid(
  mtry = c(2:6),
  min.node.size = c(1, 3, 5, 10, 15), 
  replace = c(TRUE, FALSE),                               
  sample.fraction = c(.5, .63, .8),                       
  rmse = NA)

# execute full cartesian grid search
for(i in seq_len(nrow(hyper_grid))) {
  # fit model for ith hyperparameter combination
  fit <- ranger(
    formula         = C.bisinuatus ~ ., 
    data            = cht_data, 
    num.trees       = 2500,
    mtry            = hyper_grid$mtry[i],
    min.node.size   = hyper_grid$min.node.size[i],
    replace         = hyper_grid$replace[i],
    sample.fraction = hyper_grid$sample.fraction[i],
    verbose         = FALSE,
    seed            = 123,
    #respect.unordered.factors = F,
  )
  # export OOB error 
  hyper_grid$rmse[i] <- sqrt(fit$prediction.error)}

# assess top 10 models
hyper_grid %>%
  arrange(rmse) %>%
  mutate(perc_gain = (default_rmse - rmse) / default_rmse * 100) %>%
  head(10)

# re-run model -- as there was no significant improve, go with default parameters ##
 cht_rf2 <- ranger(
  formula = C.bisinuatus ~ ., 
  data = cht_data, 
  num.trees = 2500,
  mtry = 2,
  min.node.size = 5,
  sample.fraction = .63,
  replace = T,
  importance = "permutation",
  verbose = FALSE,
  seed  = 1238
)

print(cht_rf2)
cht_rf2[["variable.importance"]]
vip::vip(cht_rf2, num_features = 10, bar = FALSE)

### Partial plots figs:
cht1 <- cht_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "sst_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "C. bisinuatus", xlab = "SST") +
        theme_light() + #ylim(10, 30) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

cht2 <- cht_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "chla_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "C. bisinuatus", xlab = "Chla") +
        theme_light() +  # ylim(10, 30) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

cht3 <- cht_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "fwd_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "C. bisinuatus", xlab = "FwD") +
        theme_light() + #ylim(10, 30) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

cht4 <- cht_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "wf_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "C. bisinuatus", xlab = "WF") +
        theme_light() +  # ylim(10, 30) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

cht5 <- cht_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "DNC", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "C. bisinuatus", xlab = "DNC") +
        theme_light() +  #ylim(10, 30) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

cht6 <- cht_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "roughness", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "C. bisinuatus", xlab = "roughness") +
        theme_light() + #ylim(10, 30) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

cht7 <- cht_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "incl_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "C. bisinuatus", xlab = "inclination") +
        theme_light() + # ylim(10, 30) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

cht_all <- ggarrange(cht1, cht2, cht3, cht4, cht5, cht6, cht7, ncol = 3, nrow = 3, align = "hv")
cht_all

#ggsave("submission/Ecography/RF_figs/MM/MidMid-Chthamalus.png", dpi = 300, width = 11.7, height = 8.14, units = "in")

varhandle::rm.all.but(keep = c("df3"), envir=.GlobalEnv, keep_functions = F, gc_limit = 100, regex = "auto")
```

#### Mid-midlittoral: mussel Mytilaster solisianus
```{r mussel M. solisianus}

myt_data <- subset(df3, select = c(4, 19:25))
myt_data <- as.data.frame(myt_data)
str(myt_data)

# train a default random forest model
  myt_rf1 <- ranger(
  formula = M.solisianus ~ ., 
  data = myt_data,
  num.trees = 2500,
  importance = "permutation",
  seed = 4558)

print(myt_rf1)
(default_rmse <- sqrt(myt_rf1$prediction.error))# get OOB RMSE for further comparison ##

# create hyperparameter grid
hyper_grid <- expand.grid(
  mtry = c(2:6),
  min.node.size = c(1, 3, 5, 10, 15), 
  replace = c(TRUE, FALSE),                               
  sample.fraction = c(.5, .63, .8),                       
  rmse = NA)

# execute full cartesian grid search
for(i in seq_len(nrow(hyper_grid))) {
  # fit model for ith hyperparameter combination
  fit <- ranger(
    formula         = M.solisianus ~ ., 
    data            = myt_data, 
    num.trees       = 2500,
    mtry            = hyper_grid$mtry[i],
    min.node.size   = hyper_grid$min.node.size[i],
    replace         = hyper_grid$replace[i],
    sample.fraction = hyper_grid$sample.fraction[i],
    verbose         = FALSE,
    seed            = 123,
    #respect.unordered.factors = F,
  )
  # export OOB error 
  hyper_grid$rmse[i] <- sqrt(fit$prediction.error)}

# assess top 10 models
hyper_grid %>%
  arrange(rmse) %>%
  mutate(perc_gain = (default_rmse - rmse) / default_rmse * 100) %>%
  head(10)

# re-run model -- as there was no significant improve, go with default parameters ##
 myt_rf2 <- ranger(
  formula = M.solisianus ~ ., 
  data = myt_data, 
  num.trees = 2500,
  mtry = 2,
  min.node.size = 5,
  sample.fraction = .63,
  replace = T,
  importance = "permutation",
  verbose = FALSE,
  seed  = 1238)

print(myt_rf2)
myt_rf2[["variable.importance"]]
vip::vip(myt_rf2, num_features = 10, bar = FALSE)

### Partial plots figs:
myt1 <- myt_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "sst_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "M. solisianus", xlab = "SST") +
        theme_light() + #ylim(34, 55) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

myt2 <- myt_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "chla_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "M. solisianus", xlab = "Chla") +
        theme_light() +   # ylim(34, 55) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

myt3 <- myt_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "fwd_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "M. solisianus", xlab = "FwD") +
        theme_light() + #ylim(34, 55) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

myt4 <- myt_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "wf_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "M. solisianus", xlab = "WF") +
        theme_light() + #ylim(34, 55) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

myt5 <- myt_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "DNC", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "M. solisianus", xlab = "DNC") +
        theme_light() + #ylim(34, 55) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

myt6 <- myt_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "roughness", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "M. solisianus", xlab = "roughness") +
        theme_light() + #ylim(34, 55) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

myt7 <- myt_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "incl_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "M. solisianus", xlab = "inclination") +
        theme_light() + #ylim(34, 55) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

myt_all <- ggarrange(myt1, myt2, myt3, myt4, myt5, myt6, myt7, ncol = 3, nrow = 3, align = "hv")
myt_all

#ggsave("submission/Ecography/RF_figs/MM/MidMid-Mytilus.png", dpi = 300, width = 11.7, height = 8.14, units = "in")

varhandle::rm.all.but(keep = c("mid_teste"), envir=.GlobalEnv, keep_functions = F, gc_limit = 100, regex = "auto")
```

### Mid-Midlittoral: barnacle Tetraclita
```{r Tetraclita stalactifera}

tet_data <- subset(df3, select = c(6, 19:25))
tet_data <- as.data.frame(tet_data)
str(tet_data)

# train a default random forest model
  tet_rf1 <- ranger(
  formula = T.stalactifera ~ ., 
  data = tet_data,
  num.trees = 2500,
  importance = "permutation",
  seed = 1238)

print(tet_rf1)
(default_rmse <- sqrt(tet_rf1$prediction.error))# get OOB RMSE for further comparison ##

# create hyperparameter grid
hyper_grid <- expand.grid(
  mtry = c(2:6),
  min.node.size = c(1, 3, 5, 10, 15), 
  replace = c(TRUE, FALSE),                               
  sample.fraction = c(.5, .63, .8),                       
  rmse = NA)

# execute full cartesian grid search
for(i in seq_len(nrow(hyper_grid))) {
  # fit model for ith hyperparameter combination
  fit <- ranger(
    formula         = T.stalactifera ~ ., 
    data            = tet_data, 
    num.trees       = 2500,
    mtry            = hyper_grid$mtry[i],
    min.node.size   = hyper_grid$min.node.size[i],
    replace         = hyper_grid$replace[i],
    sample.fraction = hyper_grid$sample.fraction[i],
    verbose         = FALSE,
    seed            = 123,
    #respect.unordered.factors = F,
  )
  # export OOB error 
  hyper_grid$rmse[i] <- sqrt(fit$prediction.error)}

# assess top 10 models
hyper_grid %>%
  arrange(rmse) %>%
  mutate(perc_gain = (default_rmse - rmse) / default_rmse * 100) %>%
  head(10)

# re-run model -- as there was no significant improve, go with default parameters ##
tet_rf2 <- ranger(
  formula = T.stalactifera ~ ., 
  data = tet_data, 
  num.trees = 2500,
  mtry = 2,
  min.node.size = 5,
  sample.fraction = .63,
  replace = TRUE,
  importance = "permutation",
  verbose = FALSE,
  seed  = 1238)

print(tet_rf2)
tet_rf2[["variable.importance"]]
vip::vip(tet_rf2, num_features = 10, bar = FALSE)

### Partial plots figs:
tet1 <- tet_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "sst_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "T. stalactifera", xlab = "SST") +
        theme_light() + #ylim(2, 14) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

tet2 <- tet_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "chla_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "T. stalactifera", xlab = "Chla") +
        theme_light() +  #ylim(2, 14) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

tet3 <- tet_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "fwd_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "T. stalactifera", xlab = "FwD") +
        theme_light() + #ylim(2, 14) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

tet4 <- tet_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "wf_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "T. stalactifera", xlab = "WF") +
        theme_light() + # ylim(2, 14) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

tet5 <- tet_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "DNC", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "T. stalactifera", xlab = "DNC") +
        theme_light() + #ylim(2, 14) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

tet6 <- tet_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "roughness", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "T. stalactifera", xlab = "roughness") +
        theme_light() +# ylim(2, 14) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

tet7 <- tet_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "incl_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "T. stalactifera", xlab = "inclination") +
        theme_light() + #ylim(2, 14) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

tet_all <- ggarrange(tet1, tet2, tet3, tet4, tet5, tet6, tet7, ncol = 3, nrow = 3, align = "hv")
tet_all

#ggsave("submission/Ecography/RF_figs/MM/MidMid-Tetraclita.png", dpi = 300, width = 11.7, height = 8.14, units = "in")

varhandle::rm.all.but(keep = c("df3"), envir=.GlobalEnv, keep_functions = F, gc_limit = 100, regex = "auto")
```

## Mid-Midlittoral: bare rock
```{r MidMid bare rock}

bareMid_data <- subset(df3, select = c(16, 19:25))
bareMid_data <- as.data.frame(bareMid_data)
str(bareMid_data)

# train a default random forest model
  bare_rf1 <- ranger(
  formula = bare_rock ~ ., 
  data = bareMid_data,
  num.trees = 2500,
  importance = "permutation",
  seed = 1288)

print(bare_rf1)
(default_rmse <- sqrt(bare_rf1$prediction.error))# get OOB RMSE for further comparison ##

# create hyperparameter grid
hyper_grid <- expand.grid(
  mtry = c(2:6),
  min.node.size = c(1, 3, 5, 10, 15), 
  replace = c(TRUE, FALSE),                               
  sample.fraction = c(.5, .63, .8),                       
  rmse = NA)

# execute full cartesian grid search
for(i in seq_len(nrow(hyper_grid))) {
  # fit model for ith hyperparameter combination
  fit <- ranger(
    formula         = bare_rock ~ ., 
    data            = bareMid_data, 
    num.trees       = 2500,
    mtry            = hyper_grid$mtry[i],
    min.node.size   = hyper_grid$min.node.size[i],
    replace         = hyper_grid$replace[i],
    sample.fraction = hyper_grid$sample.fraction[i],
    verbose         = FALSE,
    seed            = 1253,
    #respect.unordered.factors = F,
  )
  # export OOB error 
  hyper_grid$rmse[i] <- sqrt(fit$prediction.error)
}

# assess top 10 models
hyper_grid %>%
  arrange(rmse) %>%
  mutate(perc_gain = (default_rmse - rmse) / default_rmse * 100) %>%
  head(10)

# re-run model -- as there was no significant improve, go with default parameters ##
bare_rf2 <- ranger(
  formula = bare_rock ~ ., 
  data = bareMid_data, 
  num.trees = 2500,
  mtry = 2,
  min.node.size = 5,
  sample.fraction = .63,
  replace = T,
  importance = "permutation",
  verbose = FALSE,
  seed  = 5588)

print(bare_rf2)
bare_rf2[["variable.importance"]]
vip::vip(bare_rf2, num_features = 10, bar = FALSE)

### Partial plots figs:
bare1 <- bare_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "sst_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "Bare rock", xlab = "SST") +
        theme_light()  + #ylim(20,37) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

bare2 <- bare_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "chla_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "Bare rock", xlab = "Chla") +
        theme_light() +  #  ylim(20,37) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

bare3 <- bare_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "fwd_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "Bare rock", xlab = "FwD") +
        theme_light() + # ylim(20,37) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

bare4 <- bare_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "wf_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "Bare rock", xlab = "WF") +
        theme_light() +  #ylim(20,37) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

bare5 <- bare_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "DNC", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "Bare rock", xlab = "DNC") +
        theme_light() +  # ylim(20, 37) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

bare6 <- bare_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "roughness", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "Bare rock", xlab = "roughness") +
        theme_light() +  #ylim(20, 37) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

bare7 <- bare_rf2 %>%  # the %>% operator is read as "and then"
        partial(pred.var = "incl_mean", grid.resolution = 20) %>%
        autoplot(smooth = TRUE, ylab = "Bare rock", xlab = "inclination") +
        theme_light() +  # ylim(20,60) +
  theme(axis.text.x = element_text(size=14, color="black"), 
        axis.text.y = element_text(size=14, color="black"),
        axis.title.x = element_text(color="black", size=15),
        axis.title.y = element_text(color="black", size=15))+
        ggtitle("")

bare_all <- ggarrange(bare1, bare2, bare3, bare4, bare5, bare6, bare7, ncol = 3, nrow = 3, align = "hv")
bare_all

#ggsave("submission/Ecography/RF_figs/MM/MidMid-bare-rock.png", dpi = 300, width = 11.7, height = 8.14, units = "in")

varhandle::rm.all.but(keep = c("df3"), envir=.GlobalEnv, keep_functions = F, gc_limit = 100, regex = "auto")
rm(mid_teste)
```

## The end =)